// Code generated by ndpgen. DO NOT EDIT.
//
// This file provides stub implementations for non-WASM platforms.
// It allows Go plugins to compile and run tests outside of WASM,
// but the actual functionality is only available in WASM builds.
//
//go:build !wasip1

package action

// ActionRequest identifies which declared action the user triggered.
type ActionRequest struct {
	// Name is the action's name, matching one declared in manifest.json's
	// "actions" array.
	Name string `json:"name"`
}

// Action is the marker interface for action plugins.
// Implement one or more of the provider interfaces below.
// Action provides on-demand plugin actions triggered by a user from the
// admin UI (e.g. a "Test Connection" button on the plugin's config page),
// as opposed to scheduled or queued execution. Plugins declare which named
// actions they support via manifest.json's "actions" array; the host only
// calls this capability for actions the plugin has declared there.
type Action interface{}

// ActionProvider provides the OnAction function.
type ActionProvider interface {
	OnAction(ActionRequest) (string, error)
}

// NotImplementedCode is the standard return code for unimplemented functions.
const NotImplementedCode int32 = -2

// Register is a no-op on non-WASM platforms.
// This stub allows code to compile outside of WASM.
func Register(_ Action) {}
