// Code generated by ndpgen. DO NOT EDIT.
//
// This file contains export wrappers for the Action capability.
// It is intended for use in Navidrome plugins built with TinyGo.
//
//go:build wasip1

package action

import (
	"github.com/navidrome/navidrome/plugins/pdk/go/pdk"
)

// ActionRequest identifies which declared action the user triggered.
type ActionRequest struct {
	// Name is the action's name, matching one declared in manifest.json's
	// "actions" array.
	Name string `json:"name"`
}

// Action is the marker interface for action plugins.
// Implement one or more of the provider interfaces below.
// Action provides on-demand plugin actions triggered by a user from the
// admin UI (e.g. a "Test Connection" button on the plugin's config page),
// as opposed to scheduled or queued execution. Plugins declare which named
// actions they support via manifest.json's "actions" array; the host only
// calls this capability for actions the plugin has declared there.
type Action interface{}

// ActionProvider provides the OnAction function.
type ActionProvider interface {
	OnAction(ActionRequest) (string, error)
} // Internal implementation holders
var (
	actionImpl func(ActionRequest) (string, error)
)

// Register registers a action implementation.
// The implementation is checked for optional provider interfaces.
func Register(impl Action) {
	if p, ok := impl.(ActionProvider); ok {
		actionImpl = p.OnAction
	}
}

// NotImplementedCode is the standard return code for unimplemented functions.
// The host recognizes this and skips the plugin gracefully.
const NotImplementedCode int32 = -2

//go:wasmexport nd_on_action
func _NdOnAction() int32 {
	if actionImpl == nil {
		// Return standard code - host will skip this plugin gracefully
		return NotImplementedCode
	}

	var input ActionRequest
	if err := pdk.InputJSON(&input); err != nil {
		pdk.SetError(err)
		return -1
	}

	output, err := actionImpl(input)
	if err != nil {
		pdk.SetError(err)
		return -1
	}

	if err := pdk.OutputJSON(output); err != nil {
		pdk.SetError(err)
		return -1
	}

	return 0
}
